# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql
  database: db/development.mysql
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: db/test.mysql

cucumber:
  <<: *test

